<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <UserSecretsId>02380c42-8c79-4aa3-873b-4f4d14d46fa5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="Usa.Smart.Core" Version="2.16.0" />
  </ItemGroup>

</Project>
